/* Generated By:JavaCC: Do not edit this line. M4ParserConstants.java */
package org.netbeans.gnu.m4.lexer.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface M4ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int LBRACKET = 3;
  /** RegularExpression Id. */
  int MLBRACKET = 4;
  /** RegularExpression Id. */
  int MRBRACKET = 5;
  /** RegularExpression Id. */
  int RBRACKET = 6;
  /** RegularExpression Id. */
  int BOOLEAN = 7;
  /** RegularExpression Id. */
  int BREAK = 8;
  /** RegularExpression Id. */
  int CASE = 9;
  /** RegularExpression Id. */
  int CHAR = 10;
  /** RegularExpression Id. */
  int CONTINUE = 11;
  /** RegularExpression Id. */
  int _DEFAULT = 12;
  /** RegularExpression Id. */
  int DO = 13;
  /** RegularExpression Id. */
  int DONE = 14;
  /** RegularExpression Id. */
  int DOUBLE = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int FINALLY = 18;
  /** RegularExpression Id. */
  int FLOAT = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int GOTO = 21;
  /** RegularExpression Id. */
  int IF = 22;
  /** RegularExpression Id. */
  int FI = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int LONG = 25;
  /** RegularExpression Id. */
  int NULL = 26;
  /** RegularExpression Id. */
  int RETURN = 27;
  /** RegularExpression Id. */
  int SHORT = 28;
  /** RegularExpression Id. */
  int SWITCH = 29;
  /** RegularExpression Id. */
  int TEST = 30;
  /** RegularExpression Id. */
  int THEN = 31;
  /** RegularExpression Id. */
  int TRUE = 32;
  /** RegularExpression Id. */
  int TRY = 33;
  /** RegularExpression Id. */
  int VOID = 34;
  /** RegularExpression Id. */
  int WHILE = 35;
  /** RegularExpression Id. */
  int LPAREN = 36;
  /** RegularExpression Id. */
  int RPAREN = 37;
  /** RegularExpression Id. */
  int LBRACE = 38;
  /** RegularExpression Id. */
  int RBRACE = 39;
  /** RegularExpression Id. */
  int SEMICOLON = 40;
  /** RegularExpression Id. */
  int COMMA = 41;
  /** RegularExpression Id. */
  int DOT = 42;
  /** RegularExpression Id. */
  int ASSIGN = 43;
  /** RegularExpression Id. */
  int LT = 44;
  /** RegularExpression Id. */
  int BANG = 45;
  /** RegularExpression Id. */
  int TILDE = 46;
  /** RegularExpression Id. */
  int HOOK = 47;
  /** RegularExpression Id. */
  int COLON = 48;
  /** RegularExpression Id. */
  int EQ = 49;
  /** RegularExpression Id. */
  int LE = 50;
  /** RegularExpression Id. */
  int GE = 51;
  /** RegularExpression Id. */
  int NE = 52;
  /** RegularExpression Id. */
  int SC_OR = 53;
  /** RegularExpression Id. */
  int SC_AND = 54;
  /** RegularExpression Id. */
  int INCR = 55;
  /** RegularExpression Id. */
  int DECR = 56;
  /** RegularExpression Id. */
  int PLUS = 57;
  /** RegularExpression Id. */
  int MINUS = 58;
  /** RegularExpression Id. */
  int STAR = 59;
  /** RegularExpression Id. */
  int SLASH = 60;
  /** RegularExpression Id. */
  int BIT_AND = 61;
  /** RegularExpression Id. */
  int BIT_OR = 62;
  /** RegularExpression Id. */
  int XOR = 63;
  /** RegularExpression Id. */
  int REM = 64;
  /** RegularExpression Id. */
  int LSHIFT = 65;
  /** RegularExpression Id. */
  int PLUSASSIGN = 66;
  /** RegularExpression Id. */
  int MINUSASSIGN = 67;
  /** RegularExpression Id. */
  int STARASSIGN = 68;
  /** RegularExpression Id. */
  int SLASHASSIGN = 69;
  /** RegularExpression Id. */
  int ANDASSIGN = 70;
  /** RegularExpression Id. */
  int ORASSIGN = 71;
  /** RegularExpression Id. */
  int XORASSIGN = 72;
  /** RegularExpression Id. */
  int REMASSIGN = 73;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 74;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 75;
  /** RegularExpression Id. */
  int ELLIPSIS = 76;
  /** RegularExpression Id. */
  int LBRACKET_QG = 77;
  /** RegularExpression Id. */
  int RBRACKET_QG = 78;
  /** RegularExpression Id. */
  int DOLLAR_QG = 79;
  /** RegularExpression Id. */
  int BANG_QG = 80;
  /** RegularExpression Id. */
  int LBRACE_QG = 81;
  /** RegularExpression Id. */
  int RBRACE_QG = 82;
  /** RegularExpression Id. */
  int EMPTY_QG = 83;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 84;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 85;
  /** RegularExpression Id. */
  int HEX_LITERAL = 86;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 87;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 88;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 89;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 90;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 91;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 92;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 93;
  /** RegularExpression Id. */
  int STRING_LITERAL = 94;
  /** RegularExpression Id. */
  int AC_ARG_VAR = 95;
  /** RegularExpression Id. */
  int AC_ARG_ENABLE = 96;
  /** RegularExpression Id. */
  int AC_ARG_PROGRAM = 97;
  /** RegularExpression Id. */
  int AC_ARG_WITH = 98;
  /** RegularExpression Id. */
  int AC_AUTOCONF_VERSION = 99;
  /** RegularExpression Id. */
  int AC_BEFORE = 100;
  /** RegularExpression Id. */
  int AC_C_BACKSLASH_A = 101;
  /** RegularExpression Id. */
  int AC_C_BIGENDIAN = 102;
  /** RegularExpression Id. */
  int AC_C_CHAR_UNSIGNED = 103;
  /** RegularExpression Id. */
  int AC_C_CONST = 104;
  /** RegularExpression Id. */
  int AC_C_FLEXIBLE_ARRAY_MEMBER = 105;
  /** RegularExpression Id. */
  int AC_C_INLINE = 106;
  /** RegularExpression Id. */
  int AC_C_PROTOTYPES = 107;
  /** RegularExpression Id. */
  int AC_C_RESTRICT = 108;
  /** RegularExpression Id. */
  int AC_C_STRINGIZE = 109;
  /** RegularExpression Id. */
  int AC_C_TYPEOF = 110;
  /** RegularExpression Id. */
  int AC_C_VARARRAYS = 111;
  /** RegularExpression Id. */
  int AC_C_VOLATILE = 112;
  /** RegularExpression Id. */
  int AC_CACHE_CHECK = 113;
  /** RegularExpression Id. */
  int AC_CACHE_LOAD = 114;
  /** RegularExpression Id. */
  int AC_CACHE_SAVE = 115;
  /** RegularExpression Id. */
  int AC_CACHE_VAL = 116;
  /** RegularExpression Id. */
  int AC_CANONICAL_BUILD = 117;
  /** RegularExpression Id. */
  int AC_CANONICAL_HOST = 118;
  /** RegularExpression Id. */
  int AC_CANONICAL_TARGET = 119;
  /** RegularExpression Id. */
  int AC_CHECK_ALIGNOF = 120;
  /** RegularExpression Id. */
  int AC_CHECK_DECL = 121;
  /** RegularExpression Id. */
  int AC_CHECK_DECLS = 122;
  /** RegularExpression Id. */
  int AC_CHECK_DECLS_ONCE = 123;
  /** RegularExpression Id. */
  int AC_CHECK_FILE = 124;
  /** RegularExpression Id. */
  int AC_CHECK_FILES = 125;
  /** RegularExpression Id. */
  int AC_CHECK_FUNC = 126;
  /** RegularExpression Id. */
  int AC_CHECK_FUNCS = 127;
  /** RegularExpression Id. */
  int AC_CHECK_FUNCS_ONCE = 128;
  /** RegularExpression Id. */
  int AC_CHECK_LIB = 129;
  /** RegularExpression Id. */
  int AC_CHECK_HEADER = 130;
  /** RegularExpression Id. */
  int AC_CHECK_HEADER_STDBOOL = 131;
  /** RegularExpression Id. */
  int AC_CHECK_HEADERS = 132;
  /** RegularExpression Id. */
  int AC_CHECK_HEADERS_ONCE = 133;
  /** RegularExpression Id. */
  int AC_CHECK_MEMBER = 134;
  /** RegularExpression Id. */
  int AC_CHECK_MEMBERS = 135;
  /** RegularExpression Id. */
  int AC_CHECK_PROG = 136;
  /** RegularExpression Id. */
  int AC_CHECK_PROGS = 137;
  /** RegularExpression Id. */
  int AC_CHECK_SIZEOF = 138;
  /** RegularExpression Id. */
  int AC_CHECK_TARGET_TOOL = 139;
  /** RegularExpression Id. */
  int AC_CHECK_TARGET_TOOLS = 140;
  /** RegularExpression Id. */
  int AC_CHECK_TYPE = 141;
  /** RegularExpression Id. */
  int AC_CHECK_TYPES = 142;
  /** RegularExpression Id. */
  int AC_CHECK_TOOL = 143;
  /** RegularExpression Id. */
  int AC_CHECK_TOOLS = 144;
  /** RegularExpression Id. */
  int AC_COMPILE_IFELSE = 145;
  /** RegularExpression Id. */
  int AC_COMPUTE_INT = 146;
  /** RegularExpression Id. */
  int AC_CONFIG_AUX_DIR = 147;
  /** RegularExpression Id. */
  int AC_CONFIG_COMMANDS = 148;
  /** RegularExpression Id. */
  int AC_CONFIG_COMMANDS_PRE = 149;
  /** RegularExpression Id. */
  int AC_CONFIG_COMMANDS_POST = 150;
  /** RegularExpression Id. */
  int AC_CONFIG_FILES = 151;
  /** RegularExpression Id. */
  int AC_CONFIG_LIBOBJ_DIR = 152;
  /** RegularExpression Id. */
  int AC_CONFIG_LINKS = 153;
  /** RegularExpression Id. */
  int AC_CONFIG_MACRO_DIR = 154;
  /** RegularExpression Id. */
  int AC_CONFIG_MACRO_DIRS = 155;
  /** RegularExpression Id. */
  int AC_CONFIG_SRCDIR = 156;
  /** RegularExpression Id. */
  int AC_CONFIG_SUBDIRS = 157;
  /** RegularExpression Id. */
  int AC_COPYRIGHT = 158;
  /** RegularExpression Id. */
  int AC_DEFINE = 159;
  /** RegularExpression Id. */
  int AC_DEFINE_UNQUOTED = 160;
  /** RegularExpression Id. */
  int AC_DEFUN = 161;
  /** RegularExpression Id. */
  int AC_DEFUN_ONCE = 162;
  /** RegularExpression Id. */
  int AC_DIAGNOSE = 163;
  /** RegularExpression Id. */
  int AC_DISABLE_OPTION_CHECKING = 164;
  /** RegularExpression Id. */
  int AC_EGREP_CPP = 165;
  /** RegularExpression Id. */
  int AC_EGREP_HEADER = 166;
  /** RegularExpression Id. */
  int AC_ERLANG_CHECK_LIB = 167;
  /** RegularExpression Id. */
  int AC_ERLANG_NEED_ERL = 168;
  /** RegularExpression Id. */
  int AC_ERLANG_NEED_ERLC = 169;
  /** RegularExpression Id. */
  int AC_ERLANG_PATH_ERL = 170;
  /** RegularExpression Id. */
  int AC_ERLANG_PATH_ERLC = 171;
  /** RegularExpression Id. */
  int AC_ERLANG_SUBST_ERTS_VER = 172;
  /** RegularExpression Id. */
  int AC_ERLANG_SUBST_INSTALL_LIB_DIR = 173;
  /** RegularExpression Id. */
  int AC_ERLANG_SUBST_INSTALL_LIB_SUBDIR = 174;
  /** RegularExpression Id. */
  int AC_ERLANG_SUBST_LIB_DIR = 175;
  /** RegularExpression Id. */
  int AC_ERLANG_SUBST_ROOT_DIR = 176;
  /** RegularExpression Id. */
  int AC_F77_DUMMY_MAIN = 177;
  /** RegularExpression Id. */
  int AC_F77_FUNC = 178;
  /** RegularExpression Id. */
  int AC_F77_IMPLICIT_NONE = 179;
  /** RegularExpression Id. */
  int AC_F77_LIBRARY_LDFLAGS = 180;
  /** RegularExpression Id. */
  int AC_F77_MAIN = 181;
  /** RegularExpression Id. */
  int AC_F77_WRAPPERS = 182;
  /** RegularExpression Id. */
  int AC_FATAL = 183;
  /** RegularExpression Id. */
  int AC_FC_CHECK_BOUNDS = 184;
  /** RegularExpression Id. */
  int AC_FC_DUMMY_MAIN = 185;
  /** RegularExpression Id. */
  int AC_FC_FIXEDFORM = 186;
  /** RegularExpression Id. */
  int AC_FC_FREEFORM = 187;
  /** RegularExpression Id. */
  int AC_FC_FUNC = 188;
  /** RegularExpression Id. */
  int AC_FC_IMPLICIT_NONE = 189;
  /** RegularExpression Id. */
  int AC_FC_LIBRARY_LDFLAGS = 190;
  /** RegularExpression Id. */
  int AC_FC_LINE_LENGTH = 191;
  /** RegularExpression Id. */
  int AC_FC_MAIN = 192;
  /** RegularExpression Id. */
  int AC_FC_MODULE_EXTENSION = 193;
  /** RegularExpression Id. */
  int AC_FC_MODULE_FLAG = 194;
  /** RegularExpression Id. */
  int AC_FC_MODULE_OUTPUT_FLAG = 195;
  /** RegularExpression Id. */
  int AC_FC_PP_DEFINE = 196;
  /** RegularExpression Id. */
  int AC_FC_PP_SRCEXT = 197;
  /** RegularExpression Id. */
  int AC_FC_SRCEXT = 198;
  /** RegularExpression Id. */
  int AC_FC_WRAPPERS = 199;
  /** RegularExpression Id. */
  int AC_FUNC_ALLOCA = 200;
  /** RegularExpression Id. */
  int AC_FUNC_CHOWN = 201;
  /** RegularExpression Id. */
  int AC_FUNC_CLOSEDIR_VOID = 202;
  /** RegularExpression Id. */
  int AC_FUNC_ERROR_AT_LINE = 203;
  /** RegularExpression Id. */
  int AC_FUNC_FNMATCH = 204;
  /** RegularExpression Id. */
  int AC_FUNC_FNMATCH_GNU = 205;
  /** RegularExpression Id. */
  int AC_FUNC_FORK = 206;
  /** RegularExpression Id. */
  int AC_FUNC_FSEEKO = 207;
  /** RegularExpression Id. */
  int AC_FUNC_GETGROUPS = 208;
  /** RegularExpression Id. */
  int AC_FUNC_GETLOADAVG = 209;
  /** RegularExpression Id. */
  int AC_FUNC_GETMNTENT = 210;
  /** RegularExpression Id. */
  int AC_FUNC_GETPGRP = 211;
  /** RegularExpression Id. */
  int AC_FUNC_LSTAT_FOLLOWS_SLASHED_SYMLINK = 212;
  /** RegularExpression Id. */
  int AC_FUNC_MALLOC = 213;
  /** RegularExpression Id. */
  int AC_FUNC_MBRTOWC = 214;
  /** RegularExpression Id. */
  int AC_FUNC_MEMCMP = 215;
  /** RegularExpression Id. */
  int AC_FUNC_MKTIME = 216;
  /** RegularExpression Id. */
  int AC_FUNC_MMAP = 217;
  /** RegularExpression Id. */
  int AC_FUNC_OBSTACK = 218;
  /** RegularExpression Id. */
  int AC_FUNC_REALLOC = 219;
  /** RegularExpression Id. */
  int AC_FUNC_SELECT_ARGTYPES = 220;
  /** RegularExpression Id. */
  int AC_FUNC_SETPGRP = 221;
  /** RegularExpression Id. */
  int AC_FUNC_STAT = 222;
  /** RegularExpression Id. */
  int AC_FUNC_LSTAT = 223;
  /** RegularExpression Id. */
  int AC_FUNC_STRCOLL = 224;
  /** RegularExpression Id. */
  int AC_FUNC_STRERROR_R = 225;
  /** RegularExpression Id. */
  int AC_FUNC_STRFTIME = 226;
  /** RegularExpression Id. */
  int AC_FUNC_STRTOD = 227;
  /** RegularExpression Id. */
  int AC_FUNC_STRTOLD = 228;
  /** RegularExpression Id. */
  int AC_FUNC_STRNLEN = 229;
  /** RegularExpression Id. */
  int AC_FUNC_UTIME_NULL = 230;
  /** RegularExpression Id. */
  int AC_FUNC_VPRINTF = 231;
  /** RegularExpression Id. */
  int AC_HEADER_ASSERT = 232;
  /** RegularExpression Id. */
  int AC_HEADER_DIRENT = 233;
  /** RegularExpression Id. */
  int AC_HEADER_MAJOR = 234;
  /** RegularExpression Id. */
  int AC_HEADER_RESOLV = 235;
  /** RegularExpression Id. */
  int AC_HEADER_STAT = 236;
  /** RegularExpression Id. */
  int AC_HEADER_STDBOOL = 237;
  /** RegularExpression Id. */
  int AC_HEADER_STDC = 238;
  /** RegularExpression Id. */
  int AC_HEADER_SYS_WAIT = 239;
  /** RegularExpression Id. */
  int AC_HEADER_TIME = 240;
  /** RegularExpression Id. */
  int AC_HEADER_TIOCGWINSZ = 241;
  /** RegularExpression Id. */
  int AC_INCLUDES_DEFAULT = 242;
  /** RegularExpression Id. */
  int AC_INIT = 243;
  /** RegularExpression Id. */
  int AC_LANG = 244;
  /** RegularExpression Id. */
  int AC_LANG_ASSERT = 245;
  /** RegularExpression Id. */
  int AC_LANG_CALL = 246;
  /** RegularExpression Id. */
  int AC_LANG_CONFTEST = 247;
  /** RegularExpression Id. */
  int AC_LANG_DEFINES_PROVIDED = 248;
  /** RegularExpression Id. */
  int AC_LANG_FUNC_LINK_TRY = 249;
  /** RegularExpression Id. */
  int AC_LANG_POP = 250;
  /** RegularExpression Id. */
  int AC_LANG_PROGRAM = 251;
  /** RegularExpression Id. */
  int AC_LANG_PUSH = 252;
  /** RegularExpression Id. */
  int AC_LANG_SOURCE = 253;
  /** RegularExpression Id. */
  int AC_LANG_WERROR = 254;
  /** RegularExpression Id. */
  int AC_LIBOBJ = 255;
  /** RegularExpression Id. */
  int AC_LIBSOURCE = 256;
  /** RegularExpression Id. */
  int AC_LIBSOURCES = 257;
  /** RegularExpression Id. */
  int AC_LINK_IFELSE = 258;
  /** RegularExpression Id. */
  int AC_MSG_CHECKING = 259;
  /** RegularExpression Id. */
  int AC_MSG_ERROR = 260;
  /** RegularExpression Id. */
  int AC_MSG_FAILURE = 261;
  /** RegularExpression Id. */
  int AC_MSG_NOTICE = 262;
  /** RegularExpression Id. */
  int AC_MSG_RESULT = 263;
  /** RegularExpression Id. */
  int AC_MSG_WARN = 264;
  /** RegularExpression Id. */
  int AC_OPENMP = 265;
  /** RegularExpression Id. */
  int AC_OUTPUT = 266;
  /** RegularExpression Id. */
  int AC_PACKAGE_BUGREPORT = 267;
  /** RegularExpression Id. */
  int AC_PACKAGE_NAME = 268;
  /** RegularExpression Id. */
  int AC_PACKAGE_STRING = 269;
  /** RegularExpression Id. */
  int AC_PACKAGE_TARNAME = 270;
  /** RegularExpression Id. */
  int AC_PACKAGE_URL = 271;
  /** RegularExpression Id. */
  int AC_PACKAGE_VERSION = 272;
  /** RegularExpression Id. */
  int AC_PATH_PROG = 273;
  /** RegularExpression Id. */
  int AC_PATH_PROGS = 274;
  /** RegularExpression Id. */
  int AC_PATH_PROGS_FEATURE_CHECK = 275;
  /** RegularExpression Id. */
  int AC_PATH_TARGET_TOOL = 276;
  /** RegularExpression Id. */
  int AC_PATH_TOOL = 277;
  /** RegularExpression Id. */
  int AC_PATH_X = 278;
  /** RegularExpression Id. */
  int AC_PATH_XTRA = 279;
  /** RegularExpression Id. */
  int AC_PREFIX_DEFAULT = 280;
  /** RegularExpression Id. */
  int AC_PREFIX_PROGRAM = 281;
  /** RegularExpression Id. */
  int AC_PREPROC_IFELSE = 282;
  /** RegularExpression Id. */
  int AC_PREREQ = 283;
  /** RegularExpression Id. */
  int AC_PRESERVE_HELP_ORDER = 284;
  /** RegularExpression Id. */
  int AC_PROG_AWK = 285;
  /** RegularExpression Id. */
  int AC_PROG_CC = 286;
  /** RegularExpression Id. */
  int AC_PROG_CC_C_O = 287;
  /** RegularExpression Id. */
  int AC_PROG_CC_C89 = 288;
  /** RegularExpression Id. */
  int AC_PROG_CC_C99 = 289;
  /** RegularExpression Id. */
  int AC_PROG_CC_STDC = 290;
  /** RegularExpression Id. */
  int AC_PROG_CPP = 291;
  /** RegularExpression Id. */
  int AC_PROG_CPP_WERROR = 292;
  /** RegularExpression Id. */
  int AC_PROG_CXX = 293;
  /** RegularExpression Id. */
  int AC_PROG_CXX_C_O = 294;
  /** RegularExpression Id. */
  int AC_PROG_CXXCPP = 295;
  /** RegularExpression Id. */
  int AC_PROG_EGREP = 296;
  /** RegularExpression Id. */
  int AC_PROG_F77 = 297;
  /** RegularExpression Id. */
  int AC_PROG_F77_C_O = 298;
  /** RegularExpression Id. */
  int AC_PROG_FC = 299;
  /** RegularExpression Id. */
  int AC_PROG_FC_C_O = 300;
  /** RegularExpression Id. */
  int AC_PROG_FGREP = 301;
  /** RegularExpression Id. */
  int AC_PROG_GCC_TRADITIONAL = 302;
  /** RegularExpression Id. */
  int AC_PROG_GO = 303;
  /** RegularExpression Id. */
  int AC_PROG_GREP = 304;
  /** RegularExpression Id. */
  int AC_PROG_INSTALL = 305;
  /** RegularExpression Id. */
  int AC_PROG_LEX = 306;
  /** RegularExpression Id. */
  int AC_PROG_LN_S = 307;
  /** RegularExpression Id. */
  int AC_PROG_MAKE_SET = 308;
  /** RegularExpression Id. */
  int AC_PROG_MKDIR_P = 309;
  /** RegularExpression Id. */
  int AC_PROG_OBJC = 310;
  /** RegularExpression Id. */
  int AC_PROG_OBJCPP = 311;
  /** RegularExpression Id. */
  int AC_PROG_OBJCXX = 312;
  /** RegularExpression Id. */
  int AC_PROG_OBJCXXCPP = 313;
  /** RegularExpression Id. */
  int AC_PROG_RANLIB = 314;
  /** RegularExpression Id. */
  int AC_PROG_SED = 315;
  /** RegularExpression Id. */
  int AC_PROG_YACC = 316;
  /** RegularExpression Id. */
  int AC_REPLACE_FNMATCH = 317;
  /** RegularExpression Id. */
  int AC_REPLACE_FUNCS = 318;
  /** RegularExpression Id. */
  int AC_REQUIRE = 319;
  /** RegularExpression Id. */
  int AC_REQUIRE_AUX_FILE = 320;
  /** RegularExpression Id. */
  int AC_REQUIRE_CPP = 321;
  /** RegularExpression Id. */
  int AC_REVISION = 322;
  /** RegularExpression Id. */
  int AC_RUN_IFELSE = 323;
  /** RegularExpression Id. */
  int AC_SEARCH_LIBS = 324;
  /** RegularExpression Id. */
  int AC_STRUCT_DIRENT_D_INO = 325;
  /** RegularExpression Id. */
  int AC_STRUCT_DIRENT_D_TYPE = 326;
  /** RegularExpression Id. */
  int AC_STRUCT_ST_BLOCKS = 327;
  /** RegularExpression Id. */
  int AC_STRUCT_TM = 328;
  /** RegularExpression Id. */
  int AC_STRUCT_TIMEZONE = 329;
  /** RegularExpression Id. */
  int AC_SUBST = 330;
  /** RegularExpression Id. */
  int AC_SUBST_FILE = 331;
  /** RegularExpression Id. */
  int AC_SYS_INTERPRETER = 332;
  /** RegularExpression Id. */
  int AC_SYS_LARGEFILE = 333;
  /** RegularExpression Id. */
  int AC_SYS_LONG_FILE_NAMES = 334;
  /** RegularExpression Id. */
  int AC_SYS_POSIX_TERMIOS = 335;
  /** RegularExpression Id. */
  int AC_TYPE_GETGROUPS = 336;
  /** RegularExpression Id. */
  int AC_TYPE_INT8_T = 337;
  /** RegularExpression Id. */
  int AC_TYPE_INT16_T = 338;
  /** RegularExpression Id. */
  int AC_TYPE_INT32_T = 339;
  /** RegularExpression Id. */
  int AC_TYPE_INT64_T = 340;
  /** RegularExpression Id. */
  int AC_TYPE_INTMAX_T = 341;
  /** RegularExpression Id. */
  int AC_TYPE_INTPTR_T = 342;
  /** RegularExpression Id. */
  int AC_TYPE_LONG_DOUBLE = 343;
  /** RegularExpression Id. */
  int AC_TYPE_LONG_DOUBLE_WIDER = 344;
  /** RegularExpression Id. */
  int AC_TYPE_LONG_LONG_INT = 345;
  /** RegularExpression Id. */
  int AC_TYPE_MBSTATE_T = 346;
  /** RegularExpression Id. */
  int AC_TYPE_MODE_T = 347;
  /** RegularExpression Id. */
  int AC_TYPE_OFF_T = 348;
  /** RegularExpression Id. */
  int AC_TYPE_PID_T = 349;
  /** RegularExpression Id. */
  int AC_TYPE_SIZE_T = 350;
  /** RegularExpression Id. */
  int AC_TYPE_SSIZE_T = 351;
  /** RegularExpression Id. */
  int AC_TYPE_UID_T = 352;
  /** RegularExpression Id. */
  int AC_TYPE_UINT8_T = 353;
  /** RegularExpression Id. */
  int AC_TYPE_UINT16_T = 354;
  /** RegularExpression Id. */
  int AC_TYPE_UINT32_T = 355;
  /** RegularExpression Id. */
  int AC_TYPE_UINT64_T = 356;
  /** RegularExpression Id. */
  int AC_TYPE_UINTMAX_T = 357;
  /** RegularExpression Id. */
  int AC_TYPE_UINTPTR_T = 358;
  /** RegularExpression Id. */
  int AC_TYPE_UNSIGNED_LONG_LONG_INT = 359;
  /** RegularExpression Id. */
  int AC_USE_SYSTEM_EXTENSIONS = 360;
  /** RegularExpression Id. */
  int AC_WARNING = 361;
  /** RegularExpression Id. */
  int AC_AIX = 362;
  /** RegularExpression Id. */
  int AC_ALLOCA = 363;
  /** RegularExpression Id. */
  int AC_ARG_ARRAY = 364;
  /** RegularExpression Id. */
  int AC_C_CROSS = 365;
  /** RegularExpression Id. */
  int AC_C_LONG_DOUBLE = 366;
  /** RegularExpression Id. */
  int AC_CANONICAL_SYSTEM = 367;
  /** RegularExpression Id. */
  int AC_CHAR_UNSIGNED = 368;
  /** RegularExpression Id. */
  int AC_CHECKING = 369;
  /** RegularExpression Id. */
  int AC_COMPILE_CHECK = 370;
  /** RegularExpression Id. */
  int AC_CONFIG_HEADERS = 371;
  /** RegularExpression Id. */
  int AC_CONST = 372;
  /** RegularExpression Id. */
  int AC_CROSS_CHECK = 373;
  /** RegularExpression Id. */
  int AC_CYGWIN = 374;
  /** RegularExpression Id. */
  int AC_DECL_SYS_SIGLIST = 375;
  /** RegularExpression Id. */
  int AC_DECL_YYTEXT = 376;
  /** RegularExpression Id. */
  int AC_DIR_HEADER = 377;
  /** RegularExpression Id. */
  int AC_DYNIX_SEQ = 378;
  /** RegularExpression Id. */
  int AC_EXEEXT = 379;
  /** RegularExpression Id. */
  int AC_EMXOS2 = 380;
  /** RegularExpression Id. */
  int AC_ENABLE = 381;
  /** RegularExpression Id. */
  int AC_ERROR = 382;
  /** RegularExpression Id. */
  int AC_FIND_X = 383;
  /** RegularExpression Id. */
  int AC_FIND_XTRA = 384;
  /** RegularExpression Id. */
  int AC_FOREACH = 385;
  /** RegularExpression Id. */
  int AC_FUNC_CHECK = 386;
  /** RegularExpression Id. */
  int AC_FUNC_SETVBUF_REVERSED = 387;
  /** RegularExpression Id. */
  int AC_FUNC_WAIT3 = 388;
  /** RegularExpression Id. */
  int AC_GCC_TRADITIONAL = 389;
  /** RegularExpression Id. */
  int AC_GETGROUPS_T = 390;
  /** RegularExpression Id. */
  int AC_GETLOADAVG = 391;
  /** RegularExpression Id. */
  int AC_GNU_SOURCE = 392;
  /** RegularExpression Id. */
  int AC_HAVE_FUNCS = 393;
  /** RegularExpression Id. */
  int AC_HAVE_HEADERS = 394;
  /** RegularExpression Id. */
  int AC_HAVE_LIBRARY = 395;
  /** RegularExpression Id. */
  int AC_HAVE_POUNDBANG = 396;
  /** RegularExpression Id. */
  int AC_HEADER_CHECK = 397;
  /** RegularExpression Id. */
  int AC_HEADER_EGREP = 398;
  /** RegularExpression Id. */
  int AC_HELP_STRING = 399;
  /** RegularExpression Id. */
  int AC_INLINE = 400;
  /** RegularExpression Id. */
  int AC_INT_16_BITS = 401;
  /** RegularExpression Id. */
  int AC_IRIX_SUN = 402;
  /** RegularExpression Id. */
  int AC_ISC_POSIX = 403;
  /** RegularExpression Id. */
  int AC_LANG_C = 404;
  /** RegularExpression Id. */
  int AC_LANG_CPLUSPLUS = 405;
  /** RegularExpression Id. */
  int AC_LANG_FORTRAN77 = 406;
  /** RegularExpression Id. */
  int AC_LANG_RESTORE = 407;
  /** RegularExpression Id. */
  int AC_LANG_SAVE = 408;
  /** RegularExpression Id. */
  int AC_LINK_FILES = 409;
  /** RegularExpression Id. */
  int AC_LN_S = 410;
  /** RegularExpression Id. */
  int AC_LONG_64_BITS = 411;
  /** RegularExpression Id. */
  int AC_LONG_DOUBLE = 412;
  /** RegularExpression Id. */
  int AC_LONG_FILE_NAMES = 413;
  /** RegularExpression Id. */
  int AC_MAJOR_HEADER = 414;
  /** RegularExpression Id. */
  int AC_MEMORY_H = 415;
  /** RegularExpression Id. */
  int AC_MINGW32 = 416;
  /** RegularExpression Id. */
  int AC_MINIX = 417;
  /** RegularExpression Id. */
  int AC_MINUS_C_MINUS_O = 418;
  /** RegularExpression Id. */
  int AC_MMAP = 419;
  /** RegularExpression Id. */
  int AC_MODE_T = 420;
  /** RegularExpression Id. */
  int AC_OBJEXT = 421;
  /** RegularExpression Id. */
  int AC_OBSOLETE = 422;
  /** RegularExpression Id. */
  int AC_OFF_T = 423;
  /** RegularExpression Id. */
  int AC_OUTPUT_COMMANDS = 424;
  /** RegularExpression Id. */
  int AC_PID_T = 425;
  /** RegularExpression Id. */
  int AC_PREFIX = 426;
  /** RegularExpression Id. */
  int AC_PROGRAMS_CHECK = 427;
  /** RegularExpression Id. */
  int AC_PROGRAMS_PATH = 428;
  /** RegularExpression Id. */
  int AC_PROGRAM_CHECK = 429;
  /** RegularExpression Id. */
  int AC_PROGRAM_EGREP = 430;
  /** RegularExpression Id. */
  int AC_PROGRAM_PATH = 431;
  /** RegularExpression Id. */
  int AC_REMOTE_TAPE = 432;
  /** RegularExpression Id. */
  int AC_RESTARTABLE_SYSCALLS = 433;
  /** RegularExpression Id. */
  int AC_RETSIGTYPE = 434;
  /** RegularExpression Id. */
  int AC_RSH = 435;
  /** RegularExpression Id. */
  int AC_SCO_INTL = 436;
  /** RegularExpression Id. */
  int AC_SETVBUF_REVERSED = 437;
  /** RegularExpression Id. */
  int AC_SET_MAKE = 438;
  /** RegularExpression Id. */
  int AC_SIZEOF_TYPE = 439;
  /** RegularExpression Id. */
  int AC_SIZE_T = 440;
  /** RegularExpression Id. */
  int AC_STAT_MACROS_BROKEN = 441;
  /** RegularExpression Id. */
  int AC_STDC_HEADERS = 442;
  /** RegularExpression Id. */
  int AC_STRCOLL = 443;
  /** RegularExpression Id. */
  int AC_STRUCT_ST_BLKSIZE = 444;
  /** RegularExpression Id. */
  int AC_STRUCT_ST_RDEV = 445;
  /** RegularExpression Id. */
  int AC_ST_BLKSIZE = 446;
  /** RegularExpression Id. */
  int AC_ST_BLOCKS = 447;
  /** RegularExpression Id. */
  int AC_ST_RDEV = 448;
  /** RegularExpression Id. */
  int AC_SYS_RESTARTABLE_SYSCALLS = 449;
  /** RegularExpression Id. */
  int AC_SYS_SIGLIST_DECLARED = 450;
  /** RegularExpression Id. */
  int AC_TEST_CPP = 451;
  /** RegularExpression Id. */
  int AC_TEST_PROGRAM = 452;
  /** RegularExpression Id. */
  int AC_TIMEZONE = 453;
  /** RegularExpression Id. */
  int AC_TIME_WITH_SYS_TIME = 454;
  /** RegularExpression Id. */
  int AC_TRY_COMPILE = 455;
  /** RegularExpression Id. */
  int AC_TRY_CPP = 456;
  /** RegularExpression Id. */
  int AC_TRY_LINK = 457;
  /** RegularExpression Id. */
  int AC_TRY_LINK_FUNC = 458;
  /** RegularExpression Id. */
  int AC_TRY_RUN = 459;
  /** RegularExpression Id. */
  int AC_TYPE_SIGNAL = 460;
  /** RegularExpression Id. */
  int AC_UID_T = 461;
  /** RegularExpression Id. */
  int AC_UNISTD_H = 462;
  /** RegularExpression Id. */
  int AC_USG = 463;
  /** RegularExpression Id. */
  int AC_UTIME_NULL = 464;
  /** RegularExpression Id. */
  int AC_VALIDATE_CACHED_SYSTEM_TUPLE = 465;
  /** RegularExpression Id. */
  int AC_VERBOSE = 466;
  /** RegularExpression Id. */
  int AC_VFORK = 467;
  /** RegularExpression Id. */
  int AC_VPRINTF = 468;
  /** RegularExpression Id. */
  int AC_WAIT3 = 469;
  /** RegularExpression Id. */
  int AC_WARN = 470;
  /** RegularExpression Id. */
  int AC_WITH = 471;
  /** RegularExpression Id. */
  int AC_WORDS_BIGENDIAN = 472;
  /** RegularExpression Id. */
  int AC_XENIX_DIR = 473;
  /** RegularExpression Id. */
  int AC_YYTEXT_POINTER = 474;
  /** RegularExpression Id. */
  int AH_BOTTOM = 475;
  /** RegularExpression Id. */
  int AH_HEADER = 476;
  /** RegularExpression Id. */
  int AH_TEMPLATE = 477;
  /** RegularExpression Id. */
  int AH_TOP = 478;
  /** RegularExpression Id. */
  int AH_VERBATIM = 479;
  /** RegularExpression Id. */
  int AM_INIT_AUTOMAKE = 480;
  /** RegularExpression Id. */
  int AM_CONDITIONAL = 481;
  /** RegularExpression Id. */
  int AM_PATH_LISPDIR = 482;
  /** RegularExpression Id. */
  int AM_PROG_AR = 483;
  /** RegularExpression Id. */
  int AM_PROG_AS = 484;
  /** RegularExpression Id. */
  int AM_PROG_CC_C_O = 485;
  /** RegularExpression Id. */
  int AM_PROG_LEX = 486;
  /** RegularExpression Id. */
  int AM_PROG_GCJ = 487;
  /** RegularExpression Id. */
  int AM_PROG_UPC = 488;
  /** RegularExpression Id. */
  int AM_MISSING_PROG = 489;
  /** RegularExpression Id. */
  int AM_SILENT_RULES = 490;
  /** RegularExpression Id. */
  int AM_WITH_DMALLOC = 491;
  /** RegularExpression Id. */
  int AM_PROG_MKDIR_P = 492;
  /** RegularExpression Id. */
  int AS_BOURNE_COMPATIBLE = 493;
  /** RegularExpression Id. */
  int AS_BOX = 494;
  /** RegularExpression Id. */
  int AS_CASE = 495;
  /** RegularExpression Id. */
  int AS_DIRNAME = 496;
  /** RegularExpression Id. */
  int AS_ECHO = 497;
  /** RegularExpression Id. */
  int AS_ECHO_N = 498;
  /** RegularExpression Id. */
  int AS_ESCAPE = 499;
  /** RegularExpression Id. */
  int AS_EXECUTABLE_P = 500;
  /** RegularExpression Id. */
  int AS_EXIT = 501;
  /** RegularExpression Id. */
  int AS_HELP_STRING = 502;
  /** RegularExpression Id. */
  int AS_IF = 503;
  /** RegularExpression Id. */
  int AS_INIT = 504;
  /** RegularExpression Id. */
  int AS_INIT_GENERATED = 505;
  /** RegularExpression Id. */
  int AS_LINENO_PREPARE = 506;
  /** RegularExpression Id. */
  int AS_LITERAL_IF = 507;
  /** RegularExpression Id. */
  int AS_LITERAL_WORD_IF = 508;
  /** RegularExpression Id. */
  int AS_ME_PREPARE = 509;
  /** RegularExpression Id. */
  int AS_MESSAGE_FD = 510;
  /** RegularExpression Id. */
  int AS_MESSAGE_LOG_FD = 511;
  /** RegularExpression Id. */
  int AS_MKDIR_P = 512;
  /** RegularExpression Id. */
  int AS_ORIGINAL_STDIN_FD = 513;
  /** RegularExpression Id. */
  int AS_SET_CATFILE = 514;
  /** RegularExpression Id. */
  int AS_SET_STATUS = 515;
  /** RegularExpression Id. */
  int AS_SHELL_SANITIZE = 516;
  /** RegularExpression Id. */
  int AS_TMPDIR = 517;
  /** RegularExpression Id. */
  int AS_TR_CPP = 518;
  /** RegularExpression Id. */
  int AS_TR_SH = 519;
  /** RegularExpression Id. */
  int AS_UNSET = 520;
  /** RegularExpression Id. */
  int AS_VAR_APPEND = 521;
  /** RegularExpression Id. */
  int AS_VAR_ARITH = 522;
  /** RegularExpression Id. */
  int AS_VAR_COPY = 523;
  /** RegularExpression Id. */
  int AS_VAR_IF = 524;
  /** RegularExpression Id. */
  int AS_VAR_POPDEF = 525;
  /** RegularExpression Id. */
  int AS_VAR_PUSHDEF = 526;
  /** RegularExpression Id. */
  int AS_VAR_SET = 527;
  /** RegularExpression Id. */
  int AS_VAR_SET_IF = 528;
  /** RegularExpression Id. */
  int AS_VAR_TEST_SET = 529;
  /** RegularExpression Id. */
  int AS_VERSION_COMPARE = 530;
  /** RegularExpression Id. */
  int AU_ALIAS = 531;
  /** RegularExpression Id. */
  int AU_DEFUN = 532;
  /** RegularExpression Id. */
  int AC_MACRO_PRIVATE = 533;
  /** RegularExpression Id. */
  int AC_MACRO = 534;
  /** RegularExpression Id. */
  int AC_VARIABLE = 535;
  /** RegularExpression Id. */
  int AH_MACRO_PRIVATE = 536;
  /** RegularExpression Id. */
  int AH_MACRO = 537;
  /** RegularExpression Id. */
  int AH_VARIABLE = 538;
  /** RegularExpression Id. */
  int AM_MACRO_PRIVATE = 539;
  /** RegularExpression Id. */
  int AM_MACRO = 540;
  /** RegularExpression Id. */
  int AM_VARIABLE = 541;
  /** RegularExpression Id. */
  int AN_MACRO_PRIVATE = 542;
  /** RegularExpression Id. */
  int AN_MACRO = 543;
  /** RegularExpression Id. */
  int AN_VARIABLE = 544;
  /** RegularExpression Id. */
  int AS_MACRO_PRIVATE = 545;
  /** RegularExpression Id. */
  int AS_MACRO = 546;
  /** RegularExpression Id. */
  int AS_VARIABLE = 547;
  /** RegularExpression Id. */
  int AU_MACRO_PRIVATE = 548;
  /** RegularExpression Id. */
  int AU_MACRO = 549;
  /** RegularExpression Id. */
  int AU_VARIABLE = 550;
  /** RegularExpression Id. */
  int AX_MACRO_PRIVATE = 551;
  /** RegularExpression Id. */
  int AX_MACRO = 552;
  /** RegularExpression Id. */
  int AX_VARIABLE = 553;
  /** RegularExpression Id. */
  int UNKNOWN_MACRO_PRIVATE = 554;
  /** RegularExpression Id. */
  int UNKNOWN_MACRO = 555;
  /** RegularExpression Id. */
  int UNKNOWN_VARIABLE = 556;
  /** RegularExpression Id. */
  int MF_MACRO_PRIVATE = 557;
  /** RegularExpression Id. */
  int MF_MACRO = 558;
  /** RegularExpression Id. */
  int IDENTIFIER = 559;
  /** RegularExpression Id. */
  int LETTER = 560;
  /** RegularExpression Id. */
  int PART_LETTER = 561;
  /** RegularExpression Id. */
  int TEXT = 563;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "\"[\"",
    "\"[\"",
    "\"]\"",
    "\"]\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"done\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"fi\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"switch\"",
    "\"test\"",
    "\"then\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"...\"",
    "\"@<:@\"",
    "\"@:>@\"",
    "\"@S|@\"",
    "\"@%:@\"",
    "\"@{:@\"",
    "\"@:}@\"",
    "\"@&t@\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "\"AC_ARG_VAR\"",
    "\"AC_ARG_ENABLE\"",
    "\"AC_ARG_PROGRAM\"",
    "\"AC_ARG_WITH\"",
    "\"AC_AUTOCONF_VERSION\"",
    "\"AC_BEFORE\"",
    "\"AC_C_BACKSLASH_A\"",
    "\"AC_C_BIGENDIAN\"",
    "\"AC_C_CHAR_UNSIGNED\"",
    "\"AC_C_CONST\"",
    "\"AC_C_FLEXIBLE_ARRAY_MEMBER\"",
    "\"AC_C_INLINE\"",
    "\"AC_C_PROTOTYPES\"",
    "\"AC_C_RESTRICT\"",
    "\"AC_C_STRINGIZE\"",
    "\"AC_C_TYPEOF\"",
    "\"AC_C_VARARRAYS\"",
    "\"AC_C_VOLATILE\"",
    "\"AC_CACHE_CHECK\"",
    "\"AC_CACHE_LOAD\"",
    "\"AC_CACHE_SAVE\"",
    "\"AC_CACHE_VAL\"",
    "\"AC_CANONICAL_BUILD\"",
    "\"AC_CANONICAL_HOST\"",
    "\"AC_CANONICAL_TARGET\"",
    "\"AC_CHECK_ALIGNOF\"",
    "\"AC_CHECK_DECL\"",
    "\"AC_CHECK_DECLS\"",
    "\"AC_CHECK_DECLS_ONCE\"",
    "\"AC_CHECK_FILE\"",
    "\"AC_CHECK_FILES\"",
    "\"AC_CHECK_FUNC\"",
    "\"AC_CHECK_FUNCS\"",
    "\"AC_CHECK_FUNCS_ONCE\"",
    "\"AC_CHECK_LIB\"",
    "\"AC_CHECK_HEADER\"",
    "\"AC_CHECK_HEADER_STDBOOL\"",
    "\"AC_CHECK_HEADERS\"",
    "\"AC_CHECK_HEADERS_ONCE\"",
    "\"AC_CHECK_MEMBER\"",
    "\"AC_CHECK_MEMBERS\"",
    "\"AC_CHECK_PROG\"",
    "\"AC_CHECK_PROGS\"",
    "\"AC_CHECK_SIZEOF\"",
    "\"AC_CHECK_TARGET_TOOL\"",
    "\"AC_CHECK_TARGET_TOOLS\"",
    "\"AC_CHECK_TYPE\"",
    "\"AC_CHECK_TYPES\"",
    "\"AC_CHECK_TOOL\"",
    "\"AC_CHECK_TOOLS\"",
    "\"AC_COMPILE_IFELSE\"",
    "\"AC_COMPUTE_INT\"",
    "\"AC_CONFIG_AUX_DIR\"",
    "\"AC_CONFIG_COMMANDS\"",
    "\"AC_CONFIG_COMMANDS_PRE\"",
    "\"AC_CONFIG_COMMANDS_POST\"",
    "\"AC_CONFIG_FILES\"",
    "\"AC_CONFIG_LIBOBJ_DIR\"",
    "\"AC_CONFIG_LINKS\"",
    "\"AC_CONFIG_MACRO_DIR\"",
    "\"AC_CONFIG_MACRO_DIRS\"",
    "\"AC_CONFIG_SRCDIR\"",
    "\"AC_CONFIG_SUBDIRS\"",
    "\"AC_COPYRIGHT\"",
    "\"AC_DEFINE\"",
    "\"AC_DEFINE_UNQUOTED\"",
    "\"AC_DEFUN\"",
    "\"AC_DEFUN_ONCE\"",
    "\"AC_DIAGNOSE\"",
    "\"AC_DISABLE_OPTION_CHECKING\"",
    "\"AC_EGREP_CPP\"",
    "\"AC_EGREP_HEADER\"",
    "\"AC_ERLANG_CHECK_LIB\"",
    "\"AC_ERLANG_NEED_ERL\"",
    "\"AC_ERLANG_NEED_ERLC\"",
    "\"AC_ERLANG_PATH_ERL\"",
    "\"AC_ERLANG_PATH_ERLC\"",
    "\"AC_ERLANG_SUBST_ERTS_VER\"",
    "\"AC_ERLANG_SUBST_INSTALL_LIB_DIR\"",
    "\"AC_ERLANG_SUBST_INSTALL_LIB_SUBDIR\"",
    "\"AC_ERLANG_SUBST_LIB_DIR\"",
    "\"AC_ERLANG_SUBST_ROOT_DIR\"",
    "\"AC_F77_DUMMY_MAIN\"",
    "\"AC_F77_FUNC\"",
    "\"AC_F77_IMPLICIT_NONE\"",
    "\"AC_F77_LIBRARY_LDFLAGS\"",
    "\"AC_F77_MAIN\"",
    "\"AC_F77_WRAPPERS\"",
    "\"AC_FATAL\"",
    "\"AC_FC_CHECK_BOUNDS\"",
    "\"AC_FC_DUMMY_MAIN\"",
    "\"AC_FC_FIXEDFORM\"",
    "\"AC_FC_FREEFORM\"",
    "\"AC_FC_FUNC\"",
    "\"AC_FC_IMPLICIT_NONE\"",
    "\"AC_FC_LIBRARY_LDFLAGS\"",
    "\"AC_FC_LINE_LENGTH\"",
    "\"AC_FC_MAIN\"",
    "\"AC_FC_MODULE_EXTENSION\"",
    "\"AC_FC_MODULE_FLAG\"",
    "\"AC_FC_MODULE_OUTPUT_FLAG\"",
    "\"AC_FC_PP_DEFINE\"",
    "\"AC_FC_PP_SRCEXT\"",
    "\"AC_FC_SRCEXT\"",
    "\"AC_FC_WRAPPERS\"",
    "\"AC_FUNC_ALLOCA\"",
    "\"AC_FUNC_CHOWN\"",
    "\"AC_FUNC_CLOSEDIR_VOID\"",
    "\"AC_FUNC_ERROR_AT_LINE\"",
    "\"AC_FUNC_FNMATCH\"",
    "\"AC_FUNC_FNMATCH_GNU\"",
    "\"AC_FUNC_FORK\"",
    "\"AC_FUNC_FSEEKO\"",
    "\"AC_FUNC_GETGROUPS\"",
    "\"AC_FUNC_GETLOADAVG\"",
    "\"AC_FUNC_GETMNTENT\"",
    "\"AC_FUNC_GETPGRP\"",
    "\"AC_FUNC_LSTAT_FOLLOWS_SLASHED_SYMLINK\"",
    "\"AC_FUNC_MALLOC\"",
    "\"AC_FUNC_MBRTOWC\"",
    "\"AC_FUNC_MEMCMP\"",
    "\"AC_FUNC_MKTIME\"",
    "\"AC_FUNC_MMAP\"",
    "\"AC_FUNC_OBSTACK\"",
    "\"AC_FUNC_REALLOC\"",
    "\"AC_FUNC_SELECT_ARGTYPES\"",
    "\"AC_FUNC_SETPGRP\"",
    "\"AC_FUNC_STAT\"",
    "\"AC_FUNC_LSTAT\"",
    "\"AC_FUNC_STRCOLL\"",
    "\"AC_FUNC_STRERROR_R\"",
    "\"AC_FUNC_STRFTIME\"",
    "\"AC_FUNC_STRTOD\"",
    "\"AC_FUNC_STRTOLD\"",
    "\"AC_FUNC_STRNLEN\"",
    "\"AC_FUNC_UTIME_NULL\"",
    "\"AC_FUNC_VPRINTF\"",
    "\"AC_HEADER_ASSERT\"",
    "\"AC_HEADER_DIRENT\"",
    "\"AC_HEADER_MAJOR\"",
    "\"AC_HEADER_RESOLV\"",
    "\"AC_HEADER_STAT\"",
    "\"AC_HEADER_STDBOOL\"",
    "\"AC_HEADER_STDC\"",
    "\"AC_HEADER_SYS_WAIT\"",
    "\"AC_HEADER_TIME\"",
    "\"AC_HEADER_TIOCGWINSZ\"",
    "\"AC_INCLUDES_DEFAULT\"",
    "\"AC_INIT\"",
    "\"AC_LANG\"",
    "\"AC_LANG_ASSERT\"",
    "\"AC_LANG_CALL\"",
    "\"AC_LANG_CONFTEST\"",
    "\"AC_LANG_DEFINES_PROVIDED\"",
    "\"AC_LANG_FUNC_LINK_TRY\"",
    "\"AC_LANG_POP\"",
    "\"AC_LANG_PROGRAM\"",
    "\"AC_LANG_PUSH\"",
    "\"AC_LANG_SOURCE\"",
    "\"AC_LANG_WERROR\"",
    "\"AC_LIBOBJ\"",
    "\"AC_LIBSOURCE\"",
    "\"AC_LIBSOURCES\"",
    "\"AC_LINK_IFELSE\"",
    "\"AC_MSG_CHECKING\"",
    "\"AC_MSG_ERROR\"",
    "\"AC_MSG_FAILURE\"",
    "\"AC_MSG_NOTICE\"",
    "\"AC_MSG_RESULT\"",
    "\"AC_MSG_WARN\"",
    "\"AC_OPENMP\"",
    "\"AC_OUTPUT\"",
    "\"AC_PACKAGE_BUGREPORT\"",
    "\"AC_PACKAGE_NAME\"",
    "\"AC_PACKAGE_STRING\"",
    "\"AC_PACKAGE_TARNAME\"",
    "\"AC_PACKAGE_URL\"",
    "\"AC_PACKAGE_VERSION\"",
    "\"AC_PATH_PROG\"",
    "\"AC_PATH_PROGS\"",
    "\"AC_PATH_PROGS_FEATURE_CHECK\"",
    "\"AC_PATH_TARGET_TOOL\"",
    "\"AC_PATH_TOOL\"",
    "\"AC_PATH_X\"",
    "\"AC_PATH_XTRA\"",
    "\"AC_PREFIX_DEFAULT\"",
    "\"AC_PREFIX_PROGRAM\"",
    "\"AC_PREPROC_IFELSE\"",
    "\"AC_PREREQ\"",
    "\"AC_PRESERVE_HELP_ORDER\"",
    "\"AC_PROG_AWK\"",
    "\"AC_PROG_CC\"",
    "\"AC_PROG_CC_C_O\"",
    "\"AC_PROG_CC_C89\"",
    "\"AC_PROG_CC_C99\"",
    "\"AC_PROG_CC_STDC\"",
    "\"AC_PROG_CPP\"",
    "\"AC_PROG_CPP_WERROR\"",
    "\"AC_PROG_CXX\"",
    "\"AC_PROG_CXX_C_O\"",
    "\"AC_PROG_CXXCPP\"",
    "\"AC_PROG_EGREP\"",
    "\"AC_PROG_F77\"",
    "\"AC_PROG_F77_C_O\"",
    "\"AC_PROG_FC\"",
    "\"AC_PROG_FC_C_O\"",
    "\"AC_PROG_FGREP\"",
    "\"AC_PROG_GCC_TRADITIONAL\"",
    "\"AC_PROG_GO\"",
    "\"AC_PROG_GREP\"",
    "\"AC_PROG_INSTALL\"",
    "\"AC_PROG_LEX\"",
    "\"AC_PROG_LN_S\"",
    "\"AC_PROG_MAKE_SET\"",
    "\"AC_PROG_MKDIR_P\"",
    "\"AC_PROG_OBJC\"",
    "\"AC_PROG_OBJCPP\"",
    "\"AC_PROG_OBJCXX\"",
    "\"AC_PROG_OBJCXXCPP\"",
    "\"AC_PROG_RANLIB\"",
    "\"AC_PROG_SED\"",
    "\"AC_PROG_YACC\"",
    "\"AC_REPLACE_FNMATCH\"",
    "\"AC_REPLACE_FUNCS\"",
    "\"AC_REQUIRE\"",
    "\"AC_REQUIRE_AUX_FILE\"",
    "\"AC_REQUIRE_CPP\"",
    "\"AC_REVISION\"",
    "\"AC_RUN_IFELSE\"",
    "\"AC_SEARCH_LIBS\"",
    "\"AC_STRUCT_DIRENT_D_INO\"",
    "\"AC_STRUCT_DIRENT_D_TYPE\"",
    "\"AC_STRUCT_ST_BLOCKS\"",
    "\"AC_STRUCT_TM\"",
    "\"AC_STRUCT_TIMEZONE\"",
    "\"AC_SUBST\"",
    "\"AC_SUBST_FILE\"",
    "\"AC_SYS_INTERPRETER\"",
    "\"AC_SYS_LARGEFILE\"",
    "\"AC_SYS_LONG_FILE_NAMES\"",
    "\"AC_SYS_POSIX_TERMIOS\"",
    "\"AC_TYPE_GETGROUPS\"",
    "\"AC_TYPE_INT8_T\"",
    "\"AC_TYPE_INT16_T\"",
    "\"AC_TYPE_INT32_T\"",
    "\"AC_TYPE_INT64_T\"",
    "\"AC_TYPE_INTMAX_T\"",
    "\"AC_TYPE_INTPTR_T\"",
    "\"AC_TYPE_LONG_DOUBLE\"",
    "\"AC_TYPE_LONG_DOUBLE_WIDER\"",
    "\"AC_TYPE_LONG_LONG_INT\"",
    "\"AC_TYPE_MBSTATE_T\"",
    "\"AC_TYPE_MODE_T\"",
    "\"AC_TYPE_OFF_T\"",
    "\"AC_TYPE_PID_T\"",
    "\"AC_TYPE_SIZE_T\"",
    "\"AC_TYPE_SSIZE_T\"",
    "\"AC_TYPE_UID_T\"",
    "\"AC_TYPE_UINT8_T\"",
    "\"AC_TYPE_UINT16_T\"",
    "\"AC_TYPE_UINT32_T\"",
    "\"AC_TYPE_UINT64_T\"",
    "\"AC_TYPE_UINTMAX_T\"",
    "\"AC_TYPE_UINTPTR_T\"",
    "\"AC_TYPE_UNSIGNED_LONG_LONG_INT\"",
    "\"AC_USE_SYSTEM_EXTENSIONS\"",
    "\"AC_WARNING\"",
    "\"AC_AIX\"",
    "\"AC_ALLOCA\"",
    "\"AC_ARG_ARRAY\"",
    "\"AC_C_CROSS\"",
    "\"AC_C_LONG_DOUBLE\"",
    "\"AC_CANONICAL_SYSTEM\"",
    "\"AC_CHAR_UNSIGNED\"",
    "\"AC_CHECKING\"",
    "\"AC_COMPILE_CHECK\"",
    "\"AC_CONFIG_HEADERS\"",
    "\"AC_CONST\"",
    "\"AC_CROSS_CHECK\"",
    "\"AC_CYGWIN\"",
    "\"AC_DECL_SYS_SIGLIST\"",
    "\"AC_DECL_YYTEXT\"",
    "\"AC_DIR_HEADER\"",
    "\"AC_DYNIX_SEQ\"",
    "\"AC_EXEEXT\"",
    "\"AC_EMXOS2\"",
    "\"AC_ENABLE\"",
    "\"AC_ERROR\"",
    "\"AC_FIND_X\"",
    "\"AC_FIND_XTRA\"",
    "\"AC_FOREACH\"",
    "\"AC_FUNC_CHECK\"",
    "\"AC_FUNC_SETVBUF_REVERSED\"",
    "\"AC_FUNC_WAIT3\"",
    "\"AC_GCC_TRADITIONAL\"",
    "\"AC_GETGROUPS_T\"",
    "\"AC_GETLOADAVG\"",
    "\"AC_GNU_SOURCE\"",
    "\"AC_HAVE_FUNCS\"",
    "\"AC_HAVE_HEADERS\"",
    "\"AC_HAVE_LIBRARY\"",
    "\"AC_HAVE_POUNDBANG\"",
    "\"AC_HEADER_CHECK\"",
    "\"AC_HEADER_EGREP\"",
    "\"AC_HELP_STRING\"",
    "\"AC_INLINE\"",
    "\"AC_INT_16_BITS\"",
    "\"AC_IRIX_SUN\"",
    "\"AC_ISC_POSIX\"",
    "\"AC_LANG_C\"",
    "\"AC_LANG_CPLUSPLUS\"",
    "\"AC_LANG_FORTRAN77\"",
    "\"AC_LANG_RESTORE\"",
    "\"AC_LANG_SAVE\"",
    "\"AC_LINK_FILES\"",
    "\"AC_LN_S\"",
    "\"AC_LONG_64_BITS\"",
    "\"AC_LONG_DOUBLE\"",
    "\"AC_LONG_FILE_NAMES\"",
    "\"AC_MAJOR_HEADER\"",
    "\"AC_MEMORY_H\"",
    "\"AC_MINGW32\"",
    "\"AC_MINIX\"",
    "\"AC_MINUS_C_MINUS_O\"",
    "\"AC_MMAP\"",
    "\"AC_MODE_T\"",
    "\"AC_OBJEXT\"",
    "\"AC_OBSOLETE\"",
    "\"AC_OFF_T\"",
    "\"AC_OUTPUT_COMMANDS\"",
    "\"AC_PID_T\"",
    "\"AC_PREFIX\"",
    "\"AC_PROGRAMS_CHECK\"",
    "\"AC_PROGRAMS_PATH\"",
    "\"AC_PROGRAM_CHECK\"",
    "\"AC_PROGRAM_EGREP\"",
    "\"AC_PROGRAM_PATH\"",
    "\"AC_REMOTE_TAPE\"",
    "\"AC_RESTARTABLE_SYSCALLS\"",
    "\"AC_RETSIGTYPE\"",
    "\"AC_RSH\"",
    "\"AC_SCO_INTL\"",
    "\"AC_SETVBUF_REVERSED\"",
    "\"AC_SET_MAKE\"",
    "\"AC_SIZEOF_TYPE\"",
    "\"AC_SIZE_T\"",
    "\"AC_STAT_MACROS_BROKEN\"",
    "\"AC_STDC_HEADERS\"",
    "\"AC_STRCOLL\"",
    "\"AC_STRUCT_ST_BLKSIZE\"",
    "\"AC_STRUCT_ST_RDEV\"",
    "\"AC_ST_BLKSIZE\"",
    "\"AC_ST_BLOCKS\"",
    "\"AC_ST_RDEV\"",
    "\"AC_SYS_RESTARTABLE_SYSCALLS\"",
    "\"AC_SYS_SIGLIST_DECLARED\"",
    "\"AC_TEST_CPP\"",
    "\"AC_TEST_PROGRAM\"",
    "\"AC_TIMEZONE\"",
    "\"AC_TIME_WITH_SYS_TIME\"",
    "\"AC_TRY_COMPILE\"",
    "\"AC_TRY_CPP\"",
    "\"AC_TRY_LINK\"",
    "\"AC_TRY_LINK_FUNC\"",
    "\"AC_TRY_RUN\"",
    "\"AC_TYPE_SIGNAL\"",
    "\"AC_UID_T\"",
    "\"AC_UNISTD_H\"",
    "\"AC_USG\"",
    "\"AC_UTIME_NULL\"",
    "\"AC_VALIDATE_CACHED_SYSTEM_TUPLE\"",
    "\"AC_VERBOSE\"",
    "\"AC_VFORK\"",
    "\"AC_VPRINTF\"",
    "\"AC_WAIT3\"",
    "\"AC_WARN\"",
    "\"AC_WITH\"",
    "\"AC_WORDS_BIGENDIAN\"",
    "\"AC_XENIX_DIR\"",
    "\"AC_YYTEXT_POINTER\"",
    "\"AH_BOTTOM\"",
    "\"AH_HEADER\"",
    "\"AH_TEMPLATE\"",
    "\"AH_TOP\"",
    "\"AH_VERBATIM\"",
    "\"AM_INIT_AUTOMAKE\"",
    "\"AM_CONDITIONAL\"",
    "\"AM_PATH_LISPDIR\"",
    "\"AM_PROG_AR\"",
    "\"AM_PROG_AS\"",
    "\"AM_PROG_CC_C_O\"",
    "\"AM_PROG_LEX\"",
    "\"AM_PROG_GCJ\"",
    "\"AM_PROG_UPC\"",
    "\"AM_MISSING_PROG\"",
    "\"AM_SILENT_RULES\"",
    "\"AM_WITH_DMALLOC\"",
    "\"AM_PROG_MKDIR_P\"",
    "\"AS_BOURNE_COMPATIBLE\"",
    "\"AS_BOX\"",
    "\"AS_CASE\"",
    "\"AS_DIRNAME\"",
    "\"AS_ECHO\"",
    "\"AS_ECHO_N\"",
    "\"AS_ESCAPE\"",
    "\"AS_EXECUTABLE_P\"",
    "\"AS_EXIT\"",
    "\"AS_HELP_STRING\"",
    "\"AS_IF\"",
    "\"AS_INIT\"",
    "\"AS_INIT_GENERATED\"",
    "\"AS_LINENO_PREPARE\"",
    "\"AS_LITERAL_IF\"",
    "\"AS_LITERAL_WORD_IF\"",
    "\"AS_ME_PREPARE\"",
    "\"AS_MESSAGE_FD\"",
    "\"AS_MESSAGE_LOG_FD\"",
    "\"AS_MKDIR_P\"",
    "\"AS_ORIGINAL_STDIN_FD\"",
    "\"AS_SET_CATFILE\"",
    "\"AS_SET_STATUS\"",
    "\"AS_SHELL_SANITIZE\"",
    "\"AS_TMPDIR\"",
    "\"AS_TR_CPP\"",
    "\"AS_TR_SH\"",
    "\"AS_UNSET\"",
    "\"AS_VAR_APPEND\"",
    "\"AS_VAR_ARITH\"",
    "\"AS_VAR_COPY\"",
    "\"AS_VAR_IF\"",
    "\"AS_VAR_POPDEF\"",
    "\"AS_VAR_PUSHDEF\"",
    "\"AS_VAR_SET\"",
    "\"AS_VAR_SET_IF\"",
    "\"AS_VAR_TEST_SET\"",
    "\"AS_VERSION_COMPARE\"",
    "\"AU_ALIAS\"",
    "\"AU_DEFUN\"",
    "<AC_MACRO_PRIVATE>",
    "<AC_MACRO>",
    "<AC_VARIABLE>",
    "<AH_MACRO_PRIVATE>",
    "<AH_MACRO>",
    "<AH_VARIABLE>",
    "<AM_MACRO_PRIVATE>",
    "<AM_MACRO>",
    "<AM_VARIABLE>",
    "<AN_MACRO_PRIVATE>",
    "<AN_MACRO>",
    "<AN_VARIABLE>",
    "<AS_MACRO_PRIVATE>",
    "<AS_MACRO>",
    "<AS_VARIABLE>",
    "<AU_MACRO_PRIVATE>",
    "<AU_MACRO>",
    "<AU_VARIABLE>",
    "<AX_MACRO_PRIVATE>",
    "<AX_MACRO>",
    "<AX_VARIABLE>",
    "<UNKNOWN_MACRO_PRIVATE>",
    "<UNKNOWN_MACRO>",
    "<UNKNOWN_VARIABLE>",
    "<MF_MACRO_PRIVATE>",
    "<MF_MACRO>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<token of kind 562>",
    "<TEXT>",
  };

}
