/* Generated By:JavaCC: Do not edit this line. M4ParserConstants.java */
package org.netbeans.gnu.m4.lexer.javacc;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface M4ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int DNL_COMMENT = 3;
  /** RegularExpression Id. */
  int LBRACKET = 4;
  /** RegularExpression Id. */
  int MLBRACKET = 5;
  /** RegularExpression Id. */
  int MRBRACKET = 6;
  /** RegularExpression Id. */
  int RBRACKET = 7;
  /** RegularExpression Id. */
  int BOOLEAN = 8;
  /** RegularExpression Id. */
  int BREAK = 9;
  /** RegularExpression Id. */
  int CASE = 10;
  /** RegularExpression Id. */
  int CHAR = 11;
  /** RegularExpression Id. */
  int CONTINUE = 12;
  /** RegularExpression Id. */
  int _DEFAULT = 13;
  /** RegularExpression Id. */
  int DO = 14;
  /** RegularExpression Id. */
  int DONE = 15;
  /** RegularExpression Id. */
  int DOUBLE = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int FALSE = 18;
  /** RegularExpression Id. */
  int FINALLY = 19;
  /** RegularExpression Id. */
  int FLOAT = 20;
  /** RegularExpression Id. */
  int FOR = 21;
  /** RegularExpression Id. */
  int GOTO = 22;
  /** RegularExpression Id. */
  int IF = 23;
  /** RegularExpression Id. */
  int FI = 24;
  /** RegularExpression Id. */
  int INT = 25;
  /** RegularExpression Id. */
  int LONG = 26;
  /** RegularExpression Id. */
  int NULL = 27;
  /** RegularExpression Id. */
  int RETURN = 28;
  /** RegularExpression Id. */
  int SHORT = 29;
  /** RegularExpression Id. */
  int SWITCH = 30;
  /** RegularExpression Id. */
  int TEST = 31;
  /** RegularExpression Id. */
  int THEN = 32;
  /** RegularExpression Id. */
  int TRUE = 33;
  /** RegularExpression Id. */
  int TRY = 34;
  /** RegularExpression Id. */
  int VOID = 35;
  /** RegularExpression Id. */
  int WHILE = 36;
  /** RegularExpression Id. */
  int LPAREN = 37;
  /** RegularExpression Id. */
  int RPAREN = 38;
  /** RegularExpression Id. */
  int LBRACE = 39;
  /** RegularExpression Id. */
  int RBRACE = 40;
  /** RegularExpression Id. */
  int SEMICOLON = 41;
  /** RegularExpression Id. */
  int COMMA = 42;
  /** RegularExpression Id. */
  int DOT = 43;
  /** RegularExpression Id. */
  int ASSIGN = 44;
  /** RegularExpression Id. */
  int LT = 45;
  /** RegularExpression Id. */
  int BANG = 46;
  /** RegularExpression Id. */
  int TILDE = 47;
  /** RegularExpression Id. */
  int HOOK = 48;
  /** RegularExpression Id. */
  int COLON = 49;
  /** RegularExpression Id. */
  int EQ = 50;
  /** RegularExpression Id. */
  int LE = 51;
  /** RegularExpression Id. */
  int GE = 52;
  /** RegularExpression Id. */
  int NE = 53;
  /** RegularExpression Id. */
  int SC_OR = 54;
  /** RegularExpression Id. */
  int SC_AND = 55;
  /** RegularExpression Id. */
  int INCR = 56;
  /** RegularExpression Id. */
  int DECR = 57;
  /** RegularExpression Id. */
  int PLUS = 58;
  /** RegularExpression Id. */
  int MINUS = 59;
  /** RegularExpression Id. */
  int STAR = 60;
  /** RegularExpression Id. */
  int SLASH = 61;
  /** RegularExpression Id. */
  int BIT_AND = 62;
  /** RegularExpression Id. */
  int BIT_OR = 63;
  /** RegularExpression Id. */
  int XOR = 64;
  /** RegularExpression Id. */
  int REM = 65;
  /** RegularExpression Id. */
  int LSHIFT = 66;
  /** RegularExpression Id. */
  int PLUSASSIGN = 67;
  /** RegularExpression Id. */
  int MINUSASSIGN = 68;
  /** RegularExpression Id. */
  int STARASSIGN = 69;
  /** RegularExpression Id. */
  int SLASHASSIGN = 70;
  /** RegularExpression Id. */
  int ANDASSIGN = 71;
  /** RegularExpression Id. */
  int ORASSIGN = 72;
  /** RegularExpression Id. */
  int XORASSIGN = 73;
  /** RegularExpression Id. */
  int REMASSIGN = 74;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 75;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 76;
  /** RegularExpression Id. */
  int ELLIPSIS = 77;
  /** RegularExpression Id. */
  int LBRACKET_QG = 78;
  /** RegularExpression Id. */
  int RBRACKET_QG = 79;
  /** RegularExpression Id. */
  int DOLLAR_QG = 80;
  /** RegularExpression Id. */
  int BANG_QG = 81;
  /** RegularExpression Id. */
  int LBRACE_QG = 82;
  /** RegularExpression Id. */
  int RBRACE_QG = 83;
  /** RegularExpression Id. */
  int EMPTY_QG = 84;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 85;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 86;
  /** RegularExpression Id. */
  int HEX_LITERAL = 87;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 88;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 89;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 90;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 91;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 92;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 93;
  /** RegularExpression Id. */
  int CHARACTER_LITERAL = 94;
  /** RegularExpression Id. */
  int STRING_LITERAL = 95;
  /** RegularExpression Id. */
  int UNKNOWN_MACRO_PRIVATE = 96;
  /** RegularExpression Id. */
  int UNKNOWN_MACRO = 97;
  /** RegularExpression Id. */
  int UNKNOWN_VARIABLE = 98;
  /** RegularExpression Id. */
  int MF_MACRO_PRIVATE = 99;
  /** RegularExpression Id. */
  int MF_MACRO = 100;
  /** RegularExpression Id. */
  int IDENTIFIER = 101;
  /** RegularExpression Id. */
  int LETTER = 102;
  /** RegularExpression Id. */
  int PART_LETTER = 103;
  /** RegularExpression Id. */
  int TEXT = 105;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int MCOMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<DNL_COMMENT>",
    "\"[\"",
    "\"[\"",
    "\"]\"",
    "\"]\"",
    "\"boolean\"",
    "\"break\"",
    "\"case\"",
    "\"char\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"done\"",
    "\"double\"",
    "\"else\"",
    "\"false\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"fi\"",
    "\"int\"",
    "\"long\"",
    "\"null\"",
    "\"return\"",
    "\"short\"",
    "\"switch\"",
    "\"test\"",
    "\"then\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"while\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"...\"",
    "\"@<:@\"",
    "\"@:>@\"",
    "\"@S|@\"",
    "\"@%:@\"",
    "\"@{:@\"",
    "\"@:}@\"",
    "\"@&t@\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<CHARACTER_LITERAL>",
    "<STRING_LITERAL>",
    "<UNKNOWN_MACRO_PRIVATE>",
    "<UNKNOWN_MACRO>",
    "<UNKNOWN_VARIABLE>",
    "<MF_MACRO_PRIVATE>",
    "<MF_MACRO>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "<token of kind 104>",
    "<TEXT>",
  };

}
